name: Main workflow
on: push
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    environment:
      name: Firebase_test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add secret
        env:
          FILE: ${{ secrets.CONFIG_FILE }}
        run: echo "$FILE" > src/firebase/config.ts
      - name: Cypress run e2e
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
      - name: Cypress run component
        uses: cypress-io/github-action@v5
        with:
          component: true
  make-bundle:
    runs-on: ubuntu-latest
    needs: run-tests
    environment:
      name: Firebase_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Add secret
        env:
          FILE: ${{ secrets.CONFIG_FILE }}
        run: echo "$FILE" > src/firebase/config.ts
      - name: Build
        run: npm run build
      - name: Upload
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build
          path: dist
